name: Update README with WordPress Links

on:
  schedule:
    - cron: '*/5 * * * *'  # 每天运行一次

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Python script to update README
        run: python update_readme.py

      - name: Commit changes
        run: |
          git config --local user.email "296303336@qq.com"
          git config --local user.name "CM"
          git add README.md
          git commit -m "Auto update README with WordPress post links"

      - name: Push changes
        env:
          # 使用从 Secrets 中读取的 GH_TOKEN
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/SpoonException/WordPress.git
          git push origin main

